language: node_js
node_js: stable
cache:
directories:
- node_modules
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm test
  - npm run build
